# Generated by Django 3.0.5 on 2020-04-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('idcategories', models.AutoField(db_column='idCategories', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
            ],
            options={
                'db_table': 'categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('favoriteid', models.AutoField(db_column='FavoriteID', primary_key=True, serialize=False)),
                ('productid', models.IntegerField(db_column='ProductID')),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('nutrigrade', models.CharField(db_column='Nutrigrade', max_length=255)),
                ('stores', models.CharField(db_column='Stores', max_length=255)),
                ('brands', models.CharField(db_column='Brands', max_length=255)),
                ('category', models.CharField(db_column='Category', max_length=255)),
                ('quantity', models.CharField(db_column='Quantity', max_length=255)),
                ('replacedid', models.IntegerField(db_column='ReplacedID')),
                ('replacedarticle', models.CharField(db_column='ReplacedArticle', max_length=255)),
                ('replacednutrigrade', models.CharField(db_column='ReplacedNutrigrade', max_length=255)),
                ('userid', models.CharField(db_column='UserID', max_length=255)),
            ],
            options={
                'db_table': 'favorites',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('idproduct', models.AutoField(db_column='idProduct', primary_key=True, serialize=False)),
                ('productname', models.CharField(db_column='ProductName', max_length=255)),
                ('stores', models.CharField(db_column='Stores', max_length=255)),
                ('brands', models.CharField(db_column='Brands', max_length=255)),
                ('nutrigrade', models.CharField(db_column='Nutrigrade', max_length=255)),
                ('category', models.CharField(db_column='Category', max_length=255)),
                ('quantity', models.CharField(db_column='Quantity', max_length=255)),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
