# Generated by Django 3.0.5 on 2020-04-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodfacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={},
        ),
        migrations.AlterModelOptions(
            name='favorites',
            options={},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
