# Generated by Django 3.0.6 on 2020-05-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodfacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorites",
            name="front_img",
            field=models.CharField(db_column="Front_img", default="", max_length=500),
        ),
    ]
