# Generated by Django 3.0.5 on 2020-04-22 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodfacts', '0002_auto_20200422_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='favorites',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
    ]
