# Generated by Django 3.0.5 on 2020-04-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfacts', '0003_auto_20200422_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brands',
            field=models.CharField(db_column='Brands', max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(db_column='Category', max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='nutrigrade',
            field=models.CharField(db_column='Nutrigrade', max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='productname',
            field=models.CharField(db_column='ProductName', max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.CharField(db_column='Quantity', max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='stores',
            field=models.CharField(db_column='Stores', max_length=500),
        ),
    ]
