# Generated by Django 3.0.5 on 2020-05-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfacts', '0004_auto_20200429_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='carbs_100g',
            field=models.IntegerField(db_column='Carbs_100g', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='energy_kcal_100g',
            field=models.IntegerField(db_column='Energy_Kcal_100g', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='fat_100g',
            field=models.IntegerField(db_column='Fat_100g', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='fiber_100g',
            field=models.IntegerField(db_column='Fiber_100g', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='front_img',
            field=models.CharField(db_column='Front_img', default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='fruit_veg_nut_100g',
            field=models.IntegerField(db_column='Fruit_Veg_Nut_100g', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='ingredients_img',
            field=models.CharField(db_column='Ingredients_img', default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='nutrition_Score_100g',
            field=models.IntegerField(db_column='Nutrition_Score_100g', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='nutrition_img',
            field=models.CharField(db_column='Nutrition_img', default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='proteins_100g',
            field=models.IntegerField(db_column='Proteins_100g', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='salt_100g',
            field=models.IntegerField(db_column='Salt_100', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='saturated_fat_100g',
            field=models.IntegerField(db_column='Saturated_Fat_100g', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='sodium_100g',
            field=models.IntegerField(db_column='Sodium_100g', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='sugars_100g',
            field=models.IntegerField(db_column='Sugars_100g', default=0),
            preserve_default=False,
        ),
    ]
