# Generated by Django 3.0.5 on 2020-05-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodfacts', '0006_auto_20200502_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='fruit_veg_nut_100g',
        ),
    ]
