# Generated by Django 3.0.5 on 2020-05-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfacts', '0007_remove_products_fruit_veg_nut_100g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='carbs_100g',
            field=models.IntegerField(db_column='Carbs_100g', max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='energy_kcal_100g',
            field=models.IntegerField(db_column='Energy_Kcal_100g', max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='fat_100g',
            field=models.IntegerField(db_column='Fat_100g', max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='fiber_100g',
            field=models.IntegerField(db_column='Fiber_100g', max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='nutrition_Score_100g',
            field=models.IntegerField(db_column='Nutrition_Score_100g', max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='proteins_100g',
            field=models.IntegerField(db_column='Proteins_100g', max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='salt_100g',
            field=models.IntegerField(db_column='Salt_100', max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='saturated_fat_100g',
            field=models.IntegerField(db_column='Saturated_Fat_100g', max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='sodium_100g',
            field=models.IntegerField(db_column='Sodium_100g', max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='sugars_100g',
            field=models.IntegerField(db_column='Sugars_100g', max_length=500),
        ),
    ]
