# Generated by Django 3.0.5 on 2020-05-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfacts', '0011_auto_20200506_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='carbs_100g',
            field=models.FloatField(db_column='Carbs_100g'),
        ),
        migrations.AlterField(
            model_name='products',
            name='energy_kcal_100g',
            field=models.FloatField(db_column='Energy_Kcal_100g'),
        ),
        migrations.AlterField(
            model_name='products',
            name='fat_100g',
            field=models.FloatField(db_column='Fat_100g'),
        ),
        migrations.AlterField(
            model_name='products',
            name='fiber_100g',
            field=models.FloatField(db_column='Fiber_100g'),
        ),
        migrations.AlterField(
            model_name='products',
            name='proteins_100g',
            field=models.FloatField(db_column='Proteins_100g'),
        ),
        migrations.AlterField(
            model_name='products',
            name='salt_100g',
            field=models.FloatField(db_column='Salt_100'),
        ),
        migrations.AlterField(
            model_name='products',
            name='saturated_fat_100g',
            field=models.FloatField(db_column='Saturated_Fat_100g'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sodium_100g',
            field=models.FloatField(db_column='Sodium_100g'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sugars_100g',
            field=models.FloatField(db_column='Sugars_100g'),
        ),
    ]
