# Generated by Django 3.0.5 on 2020-05-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfacts', '0013_products_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='url',
            field=models.CharField(db_column='url', max_length=500),
        ),
    ]
